// Main quest data
export const QUEST_DATA = [
    {
        id: 1,
        questName: "Basic Knife Skills I",
        rank: "Home Cook",
        type: "Training",
        primaryFocus: "Technique",
        secondaryFocus: "Management",
        primaryHours: 1,
        secondaryHours: 0.5,
        diceRequired: false,
        description: "Master basic vegetable cuts: rough chop, dice, and slice"
    },
    {
        "id": 2,
        "questName": "Basic Knife Skills II",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Practice advanced cuts: julienne brunoise and chiffonade"
      },
      {
        "id": 3,
        "questName": "Heat Control Fundamentals",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Practice controlling heat levels through egg cookery"
      },
      {
        "id": 4,
        "questName": "Sautéing Basics",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn proper sautéing technique using vegetables"
      },
      {
        "id": 5,
        "questName": "Boiling & Simmering",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Master cooking grains vegetables and pasta in liquid"
      },
      {
        "id": 6,
        "questName": "Baking Fundamentals",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Technique",
        "secondaryFocus": "Ingredients",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn basic baking measurements and oven management"
      },
      {
        "id": 7,
        "questName": "Salt Pepper & Acid",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Flavor",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn to use salt pepper and acid to enhance flavor"
      },
      {
        "id": 8,
        "questName": "Herbs & Spices Intro",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Flavor",
        "secondaryFocus": "Ingredients",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Explore basic herbs and spices and when to add them"
      },
      {
        "id": 9,
        "questName": "Mise en Place",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Practice proper preparation and organization of ingredients"
      },
      {
        "id": 10,
        "questName": "Kitchen Safety & Cleaning",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn safe food handling cleaning and cross-contamination prevention"
      },
      {
        "id": 11,
        "questName": "Vegetable Identification",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Ingredients",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn to identify and select common vegetables"
      },
      {
        "id": 12,
        "questName": "Protein Basics",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Ingredients",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn to identify and select basic proteins"
      },
      {
        "id": 13,
        "questName": "Pantry Organization",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Management",
        "secondaryFocus": "Ingredients",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Organize and stock a basic pantry with essential ingredients"
      },
      {
        "id": 14,
        "questName": "Recipe Reading",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn to read understand and follow basic recipes"
      },
      {
        "id": 15,
        "questName": "Flavor Balancing",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Flavor",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Practice balancing sweet sour salty and bitter flavors"
      },
      {
        "id": 16,
        "questName": "Easy Pasta Dinner",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Cook a simple pasta dish with sauce and protein"
      },
      {
        "id": 17,
        "questName": "Basic Stir Fry",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Create a simple vegetable and protein stir fry with rice"
      },
      {
        "id": 18,
        "questName": "Hearty Soup",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Make a hearty soup using vegetables and protein"
      },
      {
        "id": 19,
        "questName": "Basic Roast",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Roast a protein with vegetable sides"
      },
      {
        "id": 20,
        "questName": "Simple Breakfast",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1.5,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Prepare eggs toast and a simple side"
      },
      {
        "id": 21,
        "questName": "Basic Sandwich Lunch",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1.5,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Construct a balanced sandwich with sides"
      },
      {
        "id": 22,
        "questName": "Easy Sheet Pan Dinner",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Create a one-pan meal with protein and vegetables"
      },
      {
        "id": 23,
        "questName": "Simple Salad",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Prepare a fresh salad with homemade dressing"
      },
      {
        "id": 24,
        "questName": "Basic Vegetable Side",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Cook a simple vegetable side dish"
      },
      {
        "id": 25,
        "questName": "Easy Grain Side",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Prepare a flavorful grain side dish"
      },
      {
        "id": 26,
        "questName": "Basic Cookies",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Ingredients",
        "primaryHours": 1.5,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Bake a basic cookie recipe"
      },
      {
        "id": 27,
        "questName": "Simple Quick Bread",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1.5,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Bake banana bread zucchini bread or similar"
      },
      {
        "id": 28,
        "questName": "Basic Sauce",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Flavor",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Create a simple sauce to accompany a dish"
      },
      {
        "id": 29,
        "questName": "Local Market Visit",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Ingredients",
        "secondaryFocus": "Management",
        "primaryHours": 1.5,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Visit a farmers market and select 3 seasonal items"
      },
      {
        "id": 30,
        "questName": "Basic Cookbook Research",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Study a cookbook and select three recipes to try"
      },
      {
        "id": 31,
        "questName": "Local Restaurant Analysis",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Flavor",
        "secondaryFocus": "Technique",
        "primaryHours": 1.5,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Visit a restaurant and analyze a dish's flavors and techniques"
      },
      {
        "id": 32,
        "questName": "Kitchen Tool Research",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Research and learn about essential kitchen tools and their uses"
      },
      {
        "id": 33,
        "questName": "Roasting Vegetables",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Practice roasting various vegetables to enhance flavor"
      },
      {
        "id": 34,
        "questName": "Steaming Techniques",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn to properly steam vegetables fish and dumplings"
      },
      {
        "id": 35,
        "questName": "Pan Frying",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Master pan frying technique for proteins and vegetables"
      },
      {
        "id": 36,
        "questName": "Braising Basics",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn the fundamentals of braising tougher cuts of meat"
      },
      {
        "id": 37,
        "questName": "Measuring & Scaling",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Practice accurate measuring and recipe scaling"
      },
      {
        "id": 38,
        "questName": "Meal Prep Basics",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn to plan and prep multiple meals efficiently"
      },
      {
        "id": 39,
        "questName": "Cooking Temperatures",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn and practice proper cooking temperatures for food safety"
      },
      {
        "id": 40,
        "questName": "Umami Exploration",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Flavor",
        "secondaryFocus": "Ingredients",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Explore umami flavors and ingredients like mushrooms soy and tomatoes"
      },
      {
        "id": 41,
        "questName": "Herb Identification",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Ingredients",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn to identify and use common fresh herbs"
      },
      {
        "id": 42,
        "questName": "Spice Identification",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Ingredients",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn to identify and use common dried spices"
      },
      {
        "id": 43,
        "questName": "Grain Varieties",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Ingredients",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn about different grain varieties and cooking methods"
      },
      {
        "id": 44,
        "questName": "Kitchen Timing",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Practice coordinating multiple dishes to finish at the same time"
      },
      {
        "id": 45,
        "questName": "Taste Development",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Flavor",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Practice tasting and adjusting seasoning throughout cooking"
      },
      {
        "id": 46,
        "questName": "Simple Weeknight Meal",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Create a balanced weeknight dinner in under 45 minutes"
      },
      {
        "id": 47,
        "questName": "Basic Roast Chicken",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Roast a whole chicken with simple seasonings"
      },
      {
        "id": 48,
        "questName": "One-Pot Meal",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Create a complete meal using just one pot"
      },
      {
        "id": 49,
        "questName": "Simple Fish Dinner",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Cook a simple fish fillet with sides"
      },
      {
        "id": 50,
        "questName": "Basic Rice Bowl",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Management",
        "secondaryFocus": "Flavor",
        "primaryHours": 1.5,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Create a balanced bowl with rice protein and vegetables"
      },
      {
        "id": 51,
        "questName": "Weekend Brunch",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Prepare a multi-component brunch with protein and sides"
      },
      {
        "id": 52,
        "questName": "Simple Casserole",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Create an easy layered casserole with protein and vegetables"
      },
      {
        "id": 53,
        "questName": "Basic Tacos",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Prepare seasoned protein and toppings for tacos"
      },
      {
        "id": 54,
        "questName": "Grain Bowl",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Management",
        "secondaryFocus": "Flavor",
        "primaryHours": 1.5,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Assemble a balanced grain bowl with protein vegetables and sauce"
      },
      {
        "id": 55,
        "questName": "Beginner's Curry",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Flavor",
        "secondaryFocus": "Technique",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Create a simple curry with vegetables and/or protein"
      },
      {
        "id": 56,
        "questName": "Roasted Potatoes",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Prepare crispy roasted potatoes with herbs"
      },
      {
        "id": 57,
        "questName": "Sautéed Greens",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Sauté leafy greens with simple seasonings"
      },
      {
        "id": 58,
        "questName": "Rice Pilaf",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Prepare flavorful rice with aromatics"
      },
      {
        "id": 59,
        "questName": "Simple Fruit Dessert",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Create an easy fruit-based dessert"
      },
      {
        "id": 60,
        "questName": "Quick Bread Rolls",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1.5,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Bake simple no-yeast dinner rolls"
      },
      {
        "id": 61,
        "questName": "Vegetable Soup",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Make a simple vegetable soup from scratch"
      },
      {
        "id": 62,
        "questName": "Basic Vinaigrette",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Flavor",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Create a balanced oil and vinegar dressing"
      },
      {
        "id": 63,
        "questName": "Flavored Butters",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Flavor",
        "secondaryFocus": "Ingredients",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Make compound butters with herbs and spices"
      },
      {
        "id": 64,
        "questName": "Specialty Market Visit",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Ingredients",
        "secondaryFocus": "Flavor",
        "primaryHours": 1.5,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Visit an ethnic or specialty market and explore new ingredients"
      },
      {
        "id": 65,
        "questName": "Cooking YouTube Research",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Watch cooking tutorials and take notes on techniques"
      },
      {
        "id": 66,
        "questName": "Food Documentary",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Ingredients",
        "secondaryFocus": "Flavor",
        "primaryHours": 1.5,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Watch a food documentary and reflect on culinary traditions"
      },
      {
        "id": 67,
        "questName": "Ingredient Substitution Research",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Management",
        "secondaryFocus": "Ingredients",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Research and document common ingredient substitutions"
      },
      {
        "id": 68,
        "questName": "Storage Methods Research",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Management",
        "secondaryFocus": "Ingredients",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn about proper food storage methods and shelf life"
      },
      {
        "id": 69,
        "questName": "Basic Meat Cookery",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn basic techniques for cooking different meat cuts"
      },
      {
        "id": 70,
        "questName": "Fish Cookery Basics",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn fundamental techniques for cooking fish"
      },
      {
        "id": 71,
        "questName": "Cooking with Eggs",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Master various egg cooking techniques"
      },
      {
        "id": 72,
        "questName": "Knife Sharpening & Care",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn to maintain and sharpen kitchen knives"
      },
      {
        "id": 73,
        "questName": "Temperature Zones",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn about refrigerator temperature zones and food placement"
      },
      {
        "id": 74,
        "questName": "Vinegar Varieties",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Ingredients",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn about different vinegars and their culinary uses"
      },
      {
        "id": 75,
        "questName": "Oil Varieties",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Ingredients",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn about different cooking oils and their smoke points"
      },
      {
        "id": 76,
        "questName": "Kitchen Multitasking",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Practice managing multiple cooking tasks simultaneously"
      },
      {
        "id": 77,
        "questName": "Herb & Spice Pairing",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Flavor",
        "secondaryFocus": "Ingredients",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn which herbs and spices complement different foods"
      },
      {
        "id": 78,
        "questName": "Simple Stir-Fry Sauce",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Flavor",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Create a balanced stir-fry sauce from pantry ingredients"
      },
      {
        "id": 79,
        "questName": "Easy Vegetarian Dinner",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Ingredients",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Prepare a satisfying plant-based main dish"
      },
      {
        "id": 80,
        "questName": "Simple Noodle Bowl",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Create an Asian-inspired noodle bowl with protein and vegetables"
      },
      {
        "id": 81,
        "questName": "Basic Frittata",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1.5,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Prepare a versatile egg dish with vegetables and/or protein"
      },
      {
        "id": 82,
        "questName": "Easy Oven-Baked Protein",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Cook protein in the oven with simple seasonings"
      },
      {
        "id": 83,
        "questName": "Simple Stuffed Vegetables",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Ingredients",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Prepare vegetables stuffed with a seasoned grain and protein mixture"
      },
      {
        "id": 84,
        "questName": "Easy Flatbread Pizza",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1.5,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Assemble and bake a simple flatbread pizza with toppings"
      },
      {
        "id": 85,
        "questName": "Beginner's Baked Pasta",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Prepare a simple baked pasta dish with sauce and cheese"
      },
      {
        "id": 86,
        "questName": "Basic Quesadillas",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1.5,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Make quesadillas with protein and/or vegetables"
      },
      {
        "id": 87,
        "questName": "Beginner's Chili",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Prepare a simple meat or vegetarian chili"
      },
      {
        "id": 88,
        "questName": "Easy Grain Salad",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Prepare a cold grain salad with vegetables and dressing"
      },
      {
        "id": 89,
        "questName": "Simple Bean Side",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Cook beans with aromatics and seasonings"
      },
      {
        "id": 90,
        "questName": "Glazed Vegetables",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Prepare vegetables with a simple flavorful glaze"
      },
      {
        "id": 91,
        "questName": "Basic Mashed Potatoes",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Make creamy mashed potatoes from scratch"
      },
      {
        "id": 92,
        "questName": "Simple Coleslaw",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Prepare a basic cabbage slaw with dressing"
      },
      {
        "id": 93,
        "questName": "Roasted Vegetable Medley",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Roast a variety of seasoned vegetables together"
      },
      {
        "id": 94,
        "questName": "Basic Hummus",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Make simple hummus with variations"
      },
      {
        "id": 95,
        "questName": "Quick Pickled Vegetables",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Prepare easy refrigerator pickles"
      },
      {
        "id": 96,
        "questName": "Seasonal Ingredients Research",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Ingredients",
        "secondaryFocus": "Management",
        "primaryHours": 1.5,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Research what's in season and plan meals accordingly"
      },
      {
        "id": 97,
        "questName": "Cooking Podcast Study",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Listen to cooking podcasts and take notes on tips"
      },
      {
        "id": 98,
        "questName": "Food Science Basics",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1.5,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Research basic food science principles and cooking reactions"
      },
      {
        "id": 99,
        "questName": "Local Food Culture",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Ingredients",
        "secondaryFocus": "Flavor",
        "primaryHours": 1.5,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Research local culinary traditions and specialties"
      },
      {
        "id": 100,
        "questName": "Recipe Adaptation Study",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn principles for adapting and modifying recipes"
      },
      {
        "id": 101,
        "questName": "Basic Kitchen Math",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Practice measuring conversions and recipe scaling"
      },
      {
        "id": 102,
        "questName": "Recipe Reading & Planning",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn to read analyze and prepare for recipes efficiently"
      },
      {
        "id": 103,
        "questName": "Basic Kitchen Organization",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Optimize kitchen workspace and tool organization"
      },
      {
        "id": 104,
        "questName": "Leftover Transformation",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Management",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn techniques for repurposing leftovers creatively"
      },
      {
        "id": 105,
        "questName": "Sweet & Savory Balance",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Flavor",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Practice balancing sweet and savory elements in dishes"
      },
      {
        "id": 106,
        "questName": "Dairy Alternatives",
        "rank": "Home Cook",
        "type": "Training",
        "primaryFocus": "Ingredients",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn about and cook with plant-based dairy alternatives"
      },
      {
        "id": 107,
        "questName": "Breakfast for Dinner",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1.5,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Prepare breakfast foods as a satisfying dinner meal"
      },
      {
        "id": 108,
        "questName": "Simple Meat & Vegetable Plate",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Cook a protein with two vegetable sides"
      },
      {
        "id": 109,
        "questName": "Easy Soup & Sandwich",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1.5,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Prepare a homemade soup and complementary sandwich"
      },
      {
        "id": 110,
        "questName": "Simple Stuffed Protein",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 2,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Prepare a stuffed chicken breast pork chop or fish fillet"
      },
      {
        "id": 111,
        "questName": "Bean-Based Main",
        "rank": "Home Cook",
        "type": "Main",
        "primaryFocus": "Technique",
        "secondaryFocus": "Ingredients",
        "primaryHours": 1.5,
        "secondaryHours": 1,
        "diceRequired": true,
        "description": "Create a filling main dish centered around beans"
      },
      {
        "id": 112,
        "questName": "Quick Garlic Bread",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Prepare simple homemade garlic bread"
      },
      {
        "id": 113,
        "questName": "Basic Cornbread",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Bake classic cornbread from scratch"
      },
      {
        "id": 114,
        "questName": "Simple Fruit Salad",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Prepare a balanced fresh fruit salad"
      },
      {
        "id": 115,
        "questName": "Basic Corn Side Dish",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Prepare corn as a flavorful side dish"
      },
      {
        "id": 116,
        "questName": "Simple Fruit Crisp",
        "rank": "Home Cook",
        "type": "Side",
        "primaryFocus": "Technique",
        "secondaryFocus": "Flavor",
        "primaryHours": 1.5,
        "secondaryHours": 0.5,
        "diceRequired": true,
        "description": "Bake an easy fruit crisp with streusel topping"
      },
      {
        "id": 117,
        "questName": "Grocery Store Exploration",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Ingredients",
        "secondaryFocus": "Management",
        "primaryHours": 1.5,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Explore unfamiliar sections of your grocery store"
      },
      {
        "id": 118,
        "questName": "Kitchen Equipment Research",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Research and evaluate essential kitchen equipment"
      },
      {
        "id": 119,
        "questName": "Meal Planning Study",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Management",
        "secondaryFocus": "Ingredients",
        "primaryHours": 1.5,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Learn and practice effective meal planning strategies"
      },
      {
        "id": 120,
        "questName": "Budget Cooking Research",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Management",
        "secondaryFocus": "Ingredients",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Research techniques and recipes for economical cooking"
      },
      {
        "id": 121,
        "questName": "Food Storage Solutions",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Research and implement better food storage practices"
      },
      {
        "id": 122,
        "questName": "Knife Skills Video Study",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Technique",
        "secondaryFocus": "Management",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Watch and take notes on professional knife skills"
      },
      {
        "id": 123,
        "questName": "Chef Biography Study",
        "rank": "Home Cook",
        "type": "Explore",
        "primaryFocus": "Management",
        "secondaryFocus": "Technique",
        "primaryHours": 1,
        "secondaryHours": 0.5,
        "diceRequired": false,
        "description": "Read about famous chefs and their cooking philosophies"
      }
];

// Quest type color definitions
export const QUEST_TYPE_COLORS = {
    'Training': '#64D949', // Green
    'Main': '#5F647C',     // Dark Gray
    'Side': '#FE3E53',     // Red
    'Explore': '#23D2E2'   // Blue
};

// Helper functions for quests
export function getQuestById(id) {
    return QUEST_DATA.find(quest => quest.id === id);
}

export function getQuestsByType(type) {
    if (type === 'all') return QUEST_DATA;
    return QUEST_DATA.filter(quest => quest.type === type);
}

export function getQuestsByRank(rank) {
    return QUEST_DATA.filter(quest => quest.rank === rank);
}